### ISSUE TITLE
'MVDR' object has no attribute 'causal_process_dict'

### ISSUE THREAD

**Issue by quancs** [hangtingchen/Beam-Guided-TasNet#5]
Hello, I got this error when running your code

```
Validation sanity check: 0it [00:00, ?it/s]Traceback (most recent call last):                                                                                                                              File "/data/home/quancs/projects/Beam-Guided-TasNet/train.py", line 137, in <module>                                                                                                                       main(arg_dic)                                                                                                                                                                                          File "/data/home/quancs/projects/Beam-Guided-TasNet/train.py", line 102, in main                                                                                                                           trainer.fit(system)                                                                                                                                                                                    File "/data/home/quancs/miniconda3/envs/beam_guided_tasnet/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 853, in fit                                                             self.dp_train(model)                                                                                                                                                                                   File "/data/home/quancs/miniconda3/envs/beam_guided_tasnet/lib/python3.9/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 578, in dp_train                                              
    self.run_pretrain_routine(model)                                                                                                                                                                     
  File "/data/home/quancs/miniconda3/envs/beam_guided_tasnet/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 998, in run_pretrain_routine                                        
    eval_results = self._evaluate(model,                                                                                                                                                                 
  File "/data/home/quancs/miniconda3/envs/beam_guided_tasnet/lib/python3.9/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 277, in _evaluate                                           
    output = self.evaluation_forward(model, batch, batch_idx, dataloader_idx, test_mode)                                                                                                                 
  File "/data/home/quancs/miniconda3/envs/beam_guided_tasnet/lib/python3.9/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 424, in evaluation_forward                                  
    output = model(*args)                                                                                                                                                                                
  File "/data/home/quancs/miniconda3/envs/beam_guided_tasnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl                                                           
    return forward_call(*input, **kwargs)                                                                                                                                                                
  File "/data/home/quancs/miniconda3/envs/beam_guided_tasnet/lib/python3.9/site-packages/pytorch_lightning/overrides/data_parallel.py", line 62, in forward                                              
    return self.module.validation_step(*inputs[0], **kwargs[0])                                                                                                                                          
  File "/data/home/quancs/projects/Beam-Guided-TasNet/system.py", line 47, in validation_step       
    loss, loss_dic = self.common_step(batch, batch_nb, train=False)                                                                                                                                      
  File "/data/home/quancs/projects/Beam-Guided-TasNet/system.py", line 28, in common_step           
    self.model.mvdr.causal_process_dict['endres'] = None                                                                                                                                                 
  File "/data/home/quancs/miniconda3/envs/beam_guided_tasnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__                                                          
    raise AttributeError("'{}' object has no attribute '{}'".format(                                                                                                                                     
AttributeError: 'MVDR' object has no attribute 'causal_process_dict'

```

**Comment by hangtingchen** [comment]
sorry for this. causal_process_dict is useless. We have removed this variable.
